algorithms/urls.py
from django.urls import path
from .views import (choose_alg, HeapSort, InsertionSort,
                    ShellSort, QuickSort, MergeSort,
                    ShellSortTest, DisplayChart, HeapSortTest,
                    MergeSortTest, InsertionSortTest, QuickSortTest,
                    )

app_name = 'algor'

urlpatterns = [
    path('', choose_alg, name='choose'),
    path('heap-sort/', HeapSort.as_view(), name='heap'),
    path('insertion-sort/', InsertionSort.as_view(), name='insertion'),
    path('shell-sort/', ShellSort.as_view(), name='shell'),
    path('quick-sort/', QuickSort.as_view(), name='quick'),
    path('merge-sort/', MergeSort.as_view(), name='merge'),
    path('shell-test/', ShellSortTest.as_view(), name='shell_test'),
    path('heap-test/', HeapSortTest.as_view(), name='heap_test'),
    path('merge-test/', MergeSortTest.as_view(), name='merge_test'),
    path('insertion-test/', InsertionSortTest.as_view(), name='insertion_test'),
    path('quick-test/', QuickSortTest.as_view(), name='quick_test'),
    path('shell-chart/', DisplayChart.as_view(), name='display_chart'),
]

django_algorytmy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('algorithms.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

algorithms/models.py
from django.db import models

algorithms/views.py
from django.shortcuts import render, redirect
from django.views import View
from alg_codes.sorting_algs import shell_sort, quick_sort, insertion_sort, merge_sort, heap_sort
from django.contrib import messages
from .utils import chart_gen, sort, sort_custom_seq

global time, sorted_list, swap, comp, operations, pivots, scal, knuth, operation


def choose_alg(request):
    return render(
        request=request,
        template_name='algorithms/choose_alg.html'
    )


class HeapSort(View):

    @staticmethod
    def post(request, *args, **kwargs):
        global sorted_list, swap, comp, time
        seq = request.POST.get('seq')
        select_seq = request.POST.get('select_seq')
        length = request.POST.get('length')

        if seq:
            sorted_list, comp, swap, time, temp = sort_custom_seq(seq, heap_sort)
            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': temp,
            }
        else:
            if length and select_seq:
                length = int(length)
                if length > 100_000_000:
                    messages.add_message(request, messages.ERROR, 'Proszę podać liczbę max do miliona')
                else:
                    time, comp, swap = sort(select_seq, length, heap_sort)
                    sorted_list = '-----'
            else:
                messages.add_message(request, messages.ERROR, 'Prosze podać rodzaj ciągu')

            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': sorted_list,
            }

        return render(
            request=request,
            template_name='algorithms/sort_for_heap.html',
            context=context
        )

    @staticmethod
    def get(request, *args, **kwargs):
        return render(
            request=request,
            template_name='algorithms/sort_for_heap.html',
        )


class InsertionSort(View):

    @staticmethod
    def post(request, *args, **kwargs):
        global time, sorted_list, swap, comp
        seq = request.POST.get('seq')
        select_seq = request.POST.get('select_seq')
        length = request.POST.get('length')

        if seq:
            sorted_list, comp, swap, time, temp = sort_custom_seq(seq, insertion_sort)

            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': temp,
            }
        else:
            if length and select_seq:
                length = int(length)
                if length > 100_000_000:
                    messages.add_message(request, messages.ERROR, 'Proszę podać liczbę max do miliona')
                else:
                    time, comp, swap = sort(select_seq, length, insertion_sort)
                    sorted_list = '-----'
            else:
                messages.add_message(request, messages.ERROR, 'Prosze podać rodzaj ciągu')

            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': sorted_list,
            }

        return render(
            request=request,
            template_name='algorithms/sort_for_inst.html',
            context=context
        )

    @staticmethod
    def get(request, *args, **kwargs):
        return render(
            request=request,
            template_name='algorithms/sort_for_inst.html',
        )


class MergeSort(View):

    @staticmethod
    def post(request, *args, **kwargs):
        global sorted_list, scal, comp, time
        seq = request.POST.get('seq')
        select_seq = request.POST.get('select_seq')
        length = request.POST.get('length')

        if seq:
            sorted_list, comp, scal, time, temp = sort_custom_seq(seq, merge_sort)

            context = {
                'time': time,
                'comp': comp,
                'scal': scal,
                'sorted_list': sorted_list,
                'unsorted_list': temp,
            }
        else:
            if length and select_seq:
                length = int(length)
                if length > 100_000_000:
                    messages.add_message(request, messages.ERROR, 'Proszę podać liczbę max do miliona')
                else:
                    time, comp, scal = sort(select_seq, length, heap_sort)
                    sorted_list = '-----'
            else:
                messages.add_message(request, messages.ERROR, 'Prosze podać rodzaj ciągu')

            context = {
                'time': time,
                'comp': comp,
                'scal': scal,
                'sorted_list': sorted_list,
                'unsorted_list': sorted_list,
            }

        return render(
            request=request,
            template_name='algorithms/sort_for_merge.html',
            context=context
        )

    @staticmethod
    def get(request, *args, **kwargs):
        return render(
            request=request,
            template_name='algorithms/sort_for_merge.html',
        )


class QuickSort(View):

    @staticmethod
    def post(request, *args, **kwargs):
        global time, sorted_list, operations, pivots, comp, swap
        seq = request.POST.get('seq')
        select_seq = request.POST.get('select_seq')
        length = request.POST.get('length')

        if seq:
            sorted_list, comp, swap, pivots, time, temp = sort_custom_seq(seq, quick_sort)

            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': temp,
                'pivot': pivots
            }
        else:
            if length and select_seq:
                length = int(length)
                if length > 100_000_000:
                    messages.add_message(request, messages.ERROR, 'Proszę podać liczbę max do miliona')
                else:
                    time, comp, swap = sort(select_seq, length, quick_sort)
            else:
                messages.add_message(request, messages.ERROR, 'Prosze podać rodzaj ciągu')

            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': sorted_list,
                'pivot': []
            }

        return render(
            request=request,
            template_name='algorithms/sort_for_quick.html',
            context=context
        )

    @staticmethod
    def get(request, *args, **kwargs):
        return render(
            request=request,
            template_name='algorithms/sort_for_quick.html',
        )


class ShellSort(View):

    @staticmethod
    def post(request, *args, **kwargs):
        global time, sorted_list, knuth, operation, comp, swap
        seq = request.POST.get('seq')
        select_seq = request.POST.get('select_seq')
        length = request.POST.get('length')

        if seq:
            sorted_list, comp, swap, knuth, time, temp = sort_custom_seq(seq, quick_sort)
            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': temp,
                'knuth': knuth
            }
        else:
            if length and select_seq:
                length = int(length)
                if length > 100_000_000:
                    messages.add_message(request, messages.ERROR, 'Proszę podać liczbę max do miliona')
                else:
                    time, comp, swap = sort(select_seq, length, heap_sort)
                    sorted_list = '-----'

            else:
                messages.add_message(request, messages.ERROR, 'Prosze podać rodzaj ciągu')

            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': sorted_list,
                'knuth': []
            }

        return render(
            request=request,
            template_name='algorithms/sort_for_shell.html',
            context=context
        )

    @staticmethod
    def get(request, *args, **kwargs):
        return render(
            request=request,
            template_name='algorithms/sort_for_shell.html',
        )


class ShellSortTest(View):

    @staticmethod
    def post(request, *args, **kwargs):
        start = request.POST.get('start')
        step = request.POST.get('step')
        stop = request.POST.get('stop')

        start = int(start)
        step = int(step)
        stop = int(stop)

        if start >= 10:
            chart_title = chart_gen(start, step, stop, shell_sort, 'shell')
            request.session['chart'] = f'shell_sort_{chart_title}.png'
            return redirect('algor:display_chart')
        else:
            messages.add_message(request, messages.ERROR, 'K musi być większe lub równe 10')
            return render(
                request=request,
                template_name='algorithms/shell_test.html'
            )

    @staticmethod
    def get(request, *args, **kwargs):

        return render(
            request=request,
            template_name='algorithms/shell_test.html',
        )


class MergeSortTest(View):

    @staticmethod
    def post(request, *args, **kwargs):
        start = request.POST.get('start')
        step = request.POST.get('step')
        stop = request.POST.get('stop')

        start = int(start)
        step = int(step)
        stop = int(stop)

        if start >= 10:
            chart_title = chart_gen(start, step, stop, merge_sort, 'merge')

algorithms/templates/algorithms/choose_alg.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
       <div class="px-4 py-5 my-5 text-center">
        <div class="col-lg-6 mx-auto">
          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="{% url 'algor:merge' %}" class="btn btn-primary btn-lg px-4 gap-3">Merge Sort</a>
            <a href="{% url 'algor:insertion' %}" class="btn btn-primary btn-lg px-4 gap-3">Insertion Sort</a>
            <a href="{% url 'algor:quick' %}" class="btn btn-primary btn-lg px-4 gap-3">Quick Sort</a>
            <a href="{% url 'algor:shell' %}" class="btn btn-primary btn-lg px-4 gap-3">Shell Sort</a>
            <a href="{% url 'algor:heap' %}" class="btn btn-primary btn-lg px-4 gap-3">Heap Sort</a>
          </div>
        </div>
       </div>
{% endblock %}

algorithms/templates/algorithms/display_chart.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}Chart{% endblock %}

{% block content %}
        {% thumbnail name "1000x400" as im %}
          <img src="{{ im.url }}" alt="...">
          {% endthumbnail %}
{% endblock %}

algorithms/templates/algorithms/heap_test.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Algorytm Heap Sort</h1> <br>
    <h3>Podaj start, krok i stop</h3>
     <form class="ui large form" method="post" action="{% url 'algor:heap_test' %}">
    {% csrf_token %}
      <div style="width:800px; margin:0 auto;">
        <h4 class="mb-3">Wprowadź dane</h4>
        <form class="needs-validation" novalidate="">
            <div class="col-12">
              <label for="start" class="form-label">Start<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="start" name="start" placeholder="100" required="">

              <label for="step" class="form-label">Step<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="step" name="step" placeholder="10" required="">

              <label for="stop" class="form-label">Stop<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="stop" name="stop" placeholder="4" required="">
    <br>
    <button class="btn btn-primary btn-lg px-4 gap-3">Testuj</button><br><br>
            </div>
    </form>
      </div>
     </form>
{% endblock %}

algorithms/templates/algorithms/insertion_test.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Algorytm Insertion Sort</h1> <br>
    <h3>Podaj start, krok i stop</h3>
     <form class="ui large form" method="post" action="{% url 'algor:insertion_test' %}">
    {% csrf_token %}
      <div style="width:800px; margin:0 auto;">
        <h4 class="mb-3">Wprowadź dane</h4>
        <form class="needs-validation" novalidate="">
            <div class="col-12">
              <label for="start" class="form-label">Start<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="start" name="start" placeholder="100" required="">

              <label for="step" class="form-label">Step<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="step" name="step" placeholder="10" required="">

              <label for="stop" class="form-label">Stop<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="stop" name="stop" placeholder="4" required="">
    <br>
    <button class="btn btn-primary btn-lg px-4 gap-3">Testuj</button><br><br>
            </div>
    </form>
      </div>
     </form>
{% endblock %}

algorithms/templates/algorithms/merge_test.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Algorytm Merge Sort</h1> <br>
    <h3>Podaj start, krok i stop</h3>
     <form class="ui large form" method="post" action="{% url 'algor:merge_test' %}">
    {% csrf_token %}
      <div style="width:800px; margin:0 auto;">
        <h4 class="mb-3">Wprowadź dane</h4>
        <form class="needs-validation" novalidate="">
            <div class="col-12">
              <label for="start" class="form-label">Start<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="start" name="start" placeholder="100" required="">

              <label for="step" class="form-label">Step<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="step" name="step" placeholder="10" required="">

              <label for="stop" class="form-label">Stop<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="stop" name="stop" placeholder="4" required="">
    <br>
    <button class="btn btn-primary btn-lg px-4 gap-3">Testuj</button><br><br>
            </div>
    </form>
      </div>
     </form>
{% endblock %}

algorithms/templates/algorithms/quick_test.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Algorytm Quick Sort</h1> <br>
    <h3>Podaj start, krok i stop</h3>
     <form class="ui large form" method="post" action="{% url 'algor:quick_test' %}">
    {% csrf_token %}
      <div style="width:800px; margin:0 auto;">
        <h4 class="mb-3">Wprowadź dane</h4>
        <form class="needs-validation" novalidate="">
            <div class="col-12">
              <label for="start" class="form-label">Start<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="start" name="start" placeholder="100" required="">

              <label for="step" class="form-label">Step<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="step" name="step" placeholder="10" required="">

              <label for="stop" class="form-label">Stop<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="stop" name="stop" placeholder="4" required="">
    <br>
    <button class="btn btn-primary btn-lg px-4 gap-3">Testuj</button><br><br>
            </div>
    </form>
      </div>
     </form>
{% endblock %}

algorithms/templates/algorithms/shell_test.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h3>Podaj k - wartość początkowa(np. 100, >=10), m - mnożnik(np. 10) oraz i - liczbę iteracji(np. 4)</h3>
     <form class="ui large form" method="post" action="{% url 'algor:insertion_test' %}">
    {% csrf_token %}
      <div style="width:800px; margin:0 auto;">
        <h4 class="mb-3">Wprowadź dane</h4>
        <form class="needs-validation" novalidate="">
            <div class="col-12">
              <label for="k" class="form-label">K<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="k" name="k" placeholder="100" required="">

              <label for="m" class="form-label">M<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="m" name="m" placeholder="10" required="">

              <label for="i" class="form-label">I<span class="text-muted"></span></label>
              <input type="number" class="form-control" id="i" name="i" placeholder="4" required="">
    <br>
    <button class="btn btn-primary btn-lg px-4 gap-3">Testuj</button><br><br>
            </div>
    </form>
      </div>
     </form>
{% endblock %}

algorithms/templates/algorithms/sort_for_heap.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Algorytm Heap Sort</h1> <br>
     <form class="ui large form" method="post" action="{% url 'algor:heap' %}">
    {% csrf_token %}
      <div style="width:800px; margin:0 auto;">
        <h4 class="mb-3">Wprowadź dane</h4>
        <form class="needs-validation" novalidate="">
            <div class="col-12">
              <label for="seq" class="form-label">Ciąg wejściowy(liczby oddzielone spacjami)<span class="text-muted"></span></label>
              <input type="text" class="form-control" id="seq" name="seq" placeholder="1 12 34 5 673 8">
    <br>

    <h4>Lub wylosuj ciąg do sortowania</h4>

      <select class="form-select" aria-label="Default select example" name="select_seq">
      <option selected>Wybierz rodzaj ciągu</option>
      <option value="A">A</option>
      <option value="V">V</option>
      <option value="increase">Rosnący</option>
      <option value="decrease">Malejący</option>
      <option value="random">Losowy</option>
    </select>
    <br>
    <label for="length" class="form-label">Długość ciągu(max milion)<span class="text-muted"></span></label>
    <input type="number" class="form-control" id="length" name="length" placeholder="2500"><br>
    </div>
    <button class="btn btn-primary btn-lg px-4 gap-3">Sortuj</button><br><br>
    </form>
      </div>
     </form>

    <div class="row align-items-md-stretch">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Czas w sekundach: {{ time }}</h2>
          <h2>Liczba opercaji porównania: {{ comp }}</h2>
          <h2>Ilość zamian: {{ swap }}</h2>
          <h3>Ciąg wejściowy: {{ unsorted_list }}</h3>
          <h3>Ciąg wyjściowy: {{ sorted_list }}</h3>

        </div>
      </div>

    <div class="px-4 py-5 my-5 text-center">
        <div class="col-lg-6 mx-auto">
          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="{% url 'algor:heap_test' %}" class="btn btn-primary btn-lg px-4 gap-3">Testy</a>
          </div>
        </div>
       </div>
{% endblock %}

algorithms/templates/algorithms/sort_for_inst.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Algorytm Insertion Sort</h1> <br>
     <form class="ui large form" method="post" action="{% url 'algor:insertion' %}">
    {% csrf_token %}
      <div style="width:800px; margin:0 auto;">
        <h4 class="mb-3">Wprowadź dane</h4>
        <form class="needs-validation" novalidate="">
            <div class="col-12">
              <label for="seq" class="form-label">Ciąg wejściowy(liczby oddzielone spacjami)<span class="text-muted"></span></label>
              <input type="text" class="form-control" id="seq" name="seq" placeholder="1 12 34 5 673 8">
    <br>

    <h4>Lub wylosuj ciąg do sortowania</h4>

      <select class="form-select" aria-label="Default select example" name="select_seq">
      <option selected>Wybierz rodzaj ciągu</option>
      <option value="A">A</option>
      <option value="V">V</option>
      <option value="increase">Rosnący</option>
      <option value="decrease">Malejący</option>
      <option value="random">Losowy</option>
    </select>
    <br>
    <label for="length" class="form-label">Długość ciągu(max milion)<span class="text-muted"></span></label>
    <input type="number" class="form-control" id="length" name="length" placeholder="2500"><br>
    </div>
    <button class="btn btn-primary btn-lg px-4 gap-3">Sortuj</button><br><br>
    </form>
      </div>
     </form>

    <div class="row align-items-md-stretch">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Czas w sekundach: {{ time }}</h2>
          <h2>Liczba opercaji porównania: {{ comp }}</h2>
          <h2>Ilość zamian {{ swap }}</h2>
          <h3>Ciąg wejściowy: {{ unsorted_list }}</h3>
          <h3>Ciąg wyjściowy: {{ sorted_list }}</h3>

        </div>
      </div>

    <div class="px-4 py-5 my-5 text-center">
        <div class="col-lg-6 mx-auto">
          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="{% url 'algor:insertion_test' %}" class="btn btn-primary btn-lg px-4 gap-3">Testy</a>
          </div>
        </div>
       </div>
{% endblock %}

algorithms/templates/algorithms/sort_for_merge.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Algorytm Merge Sort</h1> <br>
     <form class="ui large form" method="post" action="{% url 'algor:merge' %}">
    {% csrf_token %}
      <div style="width:800px; margin:0 auto;">
        <h4 class="mb-3">Wprowadź dane</h4>
        <form class="needs-validation" novalidate="">
            <div class="col-12">
              <label for="seq" class="form-label">Ciąg wejściowy(liczby oddzielone spacjami)<span class="text-muted"></span></label>
              <input type="text" class="form-control" id="seq" name="seq" placeholder="1 12 34 5 673 8">
    <br>

    <h4>Lub wylosuj ciąg do sortowania</h4>

      <select class="form-select" aria-label="Default select example" name="select_seq">
      <option selected>Wybierz rodzaj ciągu</option>
      <option value="A">A</option>
      <option value="V">V</option>
      <option value="increase">Rosnący</option>
      <option value="decrease">Malejący</option>
      <option value="random">Losowy</option>
    </select>
    <br>
    <label for="length" class="form-label">Długość ciągu(max milion)<span class="text-muted"></span></label>
    <input type="number" class="form-control" id="length" name="length" placeholder="2500"><br>
    </div>
    <button class="btn btn-primary btn-lg px-4 gap-3">Sortuj</button><br><br>
    </form>
      </div>
     </form>

    <div class="row align-items-md-stretch">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Czas w sekundach: {{ time }}</h2>
          <h2>Liczba opercaji porównania: {{ comp }}</h2>
          <h2>Ilość scaleń: {{ scal }}</h2>
          <h3>Ciąg wejściowy: {{ unsorted_list }}</h3>
          <h3>Ciąg wyjściowy: {{ sorted_list }}</h3>
        </div>
      </div>

    <div class="px-4 py-5 my-5 text-center">
        <div class="col-lg-6 mx-auto">
          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="{% url 'algor:merge_test' %}" class="btn btn-primary btn-lg px-4 gap-3">Testy</a>
          </div>
        </div>
       </div>
{% endblock %}

algorithms/templates/algorithms/sort_for_quick.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Algorytm Quick Sort</h1> <br>
     <form class="ui large form" method="post" action="{% url 'algor:quick' %}">
    {% csrf_token %}
      <div style="width:800px; margin:0 auto;">
        <h4 class="mb-3">Wprowadź dane</h4>
        <form class="needs-validation" novalidate="">
            <div class="col-12">
              <label for="seq" class="form-label">Ciąg wejściowy(liczby oddzielone spacjami)<span class="text-muted"></span></label>
              <input type="text" class="form-control" id="seq" name="seq" placeholder="1 12 34 5 673 8">
    <br>

    <h4>Lub wylosuj ciąg do sortowania</h4>

      <select class="form-select" aria-label="Default select example" name="select_seq">
      <option selected>Wybierz rodzaj ciągu</option>
      <option value="A">A</option>
      <option value="V">V</option>
      <option value="increase">Rosnący</option>
      <option value="decrease">Malejący</option>
      <option value="random">Losowy</option>
    </select>
    <br>
    <label for="length" class="form-label">Długość ciągu(max milion)<span class="text-muted"></span></label>
    <input type="number" class="form-control" id="length" name="length" placeholder="2500"><br>
    </div>
    <button class="btn btn-primary btn-lg px-4 gap-3">Sortuj</button><br><br>
    </form>
      </div>
     </form>

    <div class="row align-items-md-stretch">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Czas w sekundach: {{ time }}</h2>
          <h2>Liczba opercaji porównania: {{ comp }}</h2>
          <h2>Liczba zamian: {{ swap }}</h2>
          <h3>Ciąg wejściowy: {{ unsorted_list }}</h3>
          <h3>Ciąg wyjściowy: {{ sorted_list }}</h3>
          <h3>Wartość pivota: {{ pivot }}</h3>

        </div>
      </div>

    <div class="px-4 py-5 my-5 text-center">
        <div class="col-lg-6 mx-auto">
          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="{% url 'algor:quick_test' %}" class="btn btn-primary btn-lg px-4 gap-3">Testy</a>
          </div>
        </div>
       </div>
{% endblock %}

algorithms/templates/algorithms/sort_for_shell.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Algorytm Shell Sort</h1> <br>
     <form class="ui large form" method="post" action="{% url 'algor:shell' %}">
    {% csrf_token %}
      <div style="width:800px; margin:0 auto;">
        <h4 class="mb-3">Wprowadź dane</h4>
        <form class="needs-validation" novalidate="">
            <div class="col-12">
              <label for="seq" class="form-label">Ciąg wejściowy(liczby oddzielone spacjami)<span class="text-muted"></span></label>
              <input type="text" class="form-control" id="seq" name="seq" placeholder="1 12 34 5 673 8">
    <br>

    <h4>Lub wylosuj ciąg do sortowania</h4>

      <select class="form-select" aria-label="Default select example" name="select_seq">
      <option selected>Wybierz rodzaj ciągu</option>
      <option value="A">A</option>
      <option value="V">V</option>
      <option value="increase">Rosnący</option>
      <option value="decrease">Malejący</option>
      <option value="random">Losowy</option>
    </select>
    <br>
    <label for="length" class="form-label">Długość ciągu(max milion)<span class="text-muted"></span></label>
    <input type="number" class="form-control" id="length" name="length" placeholder="2500"><br>
    </div>
    <button class="btn btn-primary btn-lg px-4 gap-3">Sortuj</button><br><br>
    </form>
      </div>
     </form>

    <div class="row align-items-md-stretch">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Czas w sekundach: {{ time }}</h2>
          <h2>Liczba opercaji porównania: {{ comp }}</h2>
          <h2>Liczba zamian: {{ swap }}</h2>
          <h3>Ciąg wejściowy: {{ unsorted_list }}</h3>
          <h3>Ciąg wyjściowy: {{ sorted_list }}</h3>
          <h3>Wartość przyrostu: {{ knuth }}</h3>

        </div>
      </div>

    <div class="px-4 py-5 my-5 text-center">
        <div class="col-lg-6 mx-auto">
          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="{% url 'algor:shell_test' %}" class="btn btn-primary btn-lg px-4 gap-3">Testy</a>
          </div>
        </div>
       </div>
{% endblock %}