algorithms/urls.py
from django.urls import path
from .views import (choose_alg, HeapSort, InsertionSort,
                    ShellSort, QuickSort, MergeSort,
                    ShellSortTest, DisplayChart, HeapSortTest,
                    MergeSortTest, InsertionSortTest, QuickSortTest,
                    )

app_name = 'algor'

urlpatterns = [
    path('', choose_alg, name='choose'),
    path('heap-sort/', HeapSort.as_view(), name='heap'),
    path('insertion-sort/', InsertionSort.as_view(), name='insertion'),
    path('shell-sort/', ShellSort.as_view(), name='shell'),
    path('quick-sort/', QuickSort.as_view(), name='quick'),
    path('merge-sort/', MergeSort.as_view(), name='merge'),
    path('shell-test/', ShellSortTest.as_view(), name='shell_test'),
    path('heap-test/', HeapSortTest.as_view(), name='heap_test'),
    path('merge-test/', MergeSortTest.as_view(), name='merge_test'),
    path('insertion-test/', InsertionSortTest.as_view(), name='insertion_test'),
    path('quick-test/', QuickSortTest.as_view(), name='quick_test'),
    path('shell-chart/', DisplayChart.as_view(), name='display_chart'),
]

django_algorytmy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('algorithms.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

algorithms/models.py
from django.db import models

algorithms/views.py
from django.shortcuts import render, redirect
from django.views import View
from alg_codes.sorting_algs import shell_sort, quick_sort, insertion_sort, merge_sort, heap_sort
from django.contrib import messages
from .utils import chart_gen, sort, sort_custom_seq

global time, sorted_list, swap, comp, operations, pivots, scal, knuth, operation


def choose_alg(request):
    return render(
        request=request,
        template_name='algorithms/choose_alg.html'
    )


class HeapSort(View):

    @staticmethod
    def post(request, *args, **kwargs):
        global sorted_list, swap, comp, time
        seq = request.POST.get('seq')
        select_seq = request.POST.get('select_seq')
        length = request.POST.get('length')

        if seq:
            sorted_list, comp, swap, time, temp = sort_custom_seq(seq, heap_sort)
            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': temp,
            }
        else:
            if length and select_seq:
                length = int(length)
                if length > 100_000_000:
                    messages.add_message(request, messages.ERROR, 'Proszę podać liczbę max do miliona')
                else:
                    time, comp, swap = sort(select_seq, length, heap_sort)
                    sorted_list = '-----'
            else:
                messages.add_message(request, messages.ERROR, 'Prosze podać rodzaj ciągu')

            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': sorted_list,
            }

        return render(
            request=request,
            template_name='algorithms/sort_for_heap.html',
            context=context
        )

    @staticmethod
    def get(request, *args, **kwargs):
        return render(
            request=request,
            template_name='algorithms/sort_for_heap.html',
        )


class InsertionSort(View):

    @staticmethod
    def post(request, *args, **kwargs):
        global time, sorted_list, swap, comp
        seq = request.POST.get('seq')
        select_seq = request.POST.get('select_seq')
        length = request.POST.get('length')

        if seq:
            sorted_list, comp, swap, time, temp = sort_custom_seq(seq, insertion_sort)

            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': temp,
            }
        else:
            if length and select_seq:
                length = int(length)
                if length > 100_000_000:
                    messages.add_message(request, messages.ERROR, 'Proszę podać liczbę max do miliona')
                else:
                    time, comp, swap = sort(select_seq, length, insertion_sort)
                    sorted_list = '-----'
            else:
                messages.add_message(request, messages.ERROR, 'Prosze podać rodzaj ciągu')

            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': sorted_list,
            }

        return render(
            request=request,
            template_name='algorithms/sort_for_inst.html',
            context=context
        )

    @staticmethod
    def get(request, *args, **kwargs):
        return render(
            request=request,
            template_name='algorithms/sort_for_inst.html',
        )


class MergeSort(View):

    @staticmethod
    def post(request, *args, **kwargs):
        global sorted_list, scal, comp, time
        seq = request.POST.get('seq')
        select_seq = request.POST.get('select_seq')
        length = request.POST.get('length')

        if seq:
            sorted_list, comp, scal, time, temp = sort_custom_seq(seq, merge_sort)

            context = {
                'time': time,
                'comp': comp,
                'scal': scal,
                'sorted_list': sorted_list,
                'unsorted_list': temp,
            }
        else:
            if length and select_seq:
                length = int(length)
                if length > 100_000_000:
                    messages.add_message(request, messages.ERROR, 'Proszę podać liczbę max do miliona')
                else:
                    time, comp, scal = sort(select_seq, length, heap_sort)
                    sorted_list = '-----'
            else:
                messages.add_message(request, messages.ERROR, 'Prosze podać rodzaj ciągu')

            context = {
                'time': time,
                'comp': comp,
                'scal': scal,
                'sorted_list': sorted_list,
                'unsorted_list': sorted_list,
            }

        return render(
            request=request,
            template_name='algorithms/sort_for_merge.html',
            context=context
        )

    @staticmethod
    def get(request, *args, **kwargs):
        return render(
            request=request,
            template_name='algorithms/sort_for_merge.html',
        )


class QuickSort(View):

    @staticmethod
    def post(request, *args, **kwargs):
        global time, sorted_list, operations, pivots, comp, swap
        seq = request.POST.get('seq')
        select_seq = request.POST.get('select_seq')
        length = request.POST.get('length')

        if seq:
            sorted_list, comp, swap, pivots, time, temp = sort_custom_seq(seq, quick_sort)

            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': temp,
                'pivot': pivots
            }
        else:
            if length and select_seq:
                length = int(length)
                if length > 100_000_000:
                    messages.add_message(request, messages.ERROR, 'Proszę podać liczbę max do miliona')
                else:
                    time, comp, swap = sort(select_seq, length, quick_sort)
            else:
                messages.add_message(request, messages.ERROR, 'Prosze podać rodzaj ciągu')

            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': sorted_list,
                'pivot': []
            }

        return render(
            request=request,
            template_name='algorithms/sort_for_quick.html',
            context=context
        )

    @staticmethod
    def get(request, *args, **kwargs):
        return render(
            request=request,
            template_name='algorithms/sort_for_quick.html',
        )


class ShellSort(View):

    @staticmethod
    def post(request, *args, **kwargs):
        global time, sorted_list, knuth, operation, comp, swap
        seq = request.POST.get('seq')
        select_seq = request.POST.get('select_seq')
        length = request.POST.get('length')

        if seq:
            sorted_list, comp, swap, knuth, time, temp = sort_custom_seq(seq, quick_sort)
            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': temp,
                'knuth': knuth
            }
        else:
            if length and select_seq:
                length = int(length)
                if length > 100_000_000:
                    messages.add_message(request, messages.ERROR, 'Proszę podać liczbę max do miliona')
                else:
                    time, comp, swap = sort(select_seq, length, heap_sort)
                    sorted_list = '-----'

            else:
                messages.add_message(request, messages.ERROR, 'Prosze podać rodzaj ciągu')

            context = {
                'time': time,
                'comp': comp,
                'swap': swap,
                'sorted_list': sorted_list,
                'unsorted_list': sorted_list,
                'knuth': []
            }

        return render(
            request=request,
            template_name='algorithms/sort_for_shell.html',
            context=context
        )

    @staticmethod
    def get(request, *args, **kwargs):
        return render(
            request=request,
            template_name='algorithms/sort_for_shell.html',
        )


class ShellSortTest(View):

    @staticmethod
    def post(request, *args, **kwargs):
        start = request.POST.get('start')
        step = request.POST.get('step')
        stop = request.POST.get('stop')

        start = int(start)
        step = int(step)
        stop = int(stop)

        if start >= 10:
            chart_title = chart_gen(start, step, stop, shell_sort, 'shell')
            request.session['chart'] = f'shell_sort_{chart_title}.png'
            return redirect('algor:display_chart')
        else:
            messages.add_message(request, messages.ERROR, 'K musi być większe lub równe 10')
            return render(
                request=request,
                template_name='algorithms/shell_test.html'
            )

    @staticmethod
    def get(request, *args, **kwargs):

        return render(
            request=request,
            template_name='algorithms/shell_test.html',
        )


class MergeSortTest(View):

    @staticmethod
    def post(request, *args, **kwargs):
        start = request.POST.get('start')
        step = request.POST.get('step')
        stop = request.POST.get('stop')

        start = int(start)
        step = int(step)
        stop = int(stop)

        if start >= 10:
            chart_title = chart_gen(start, step, stop, merge_sort, 'merge')

algorithms/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block styles %} {% endblock %}
</head>
<body>
<header>
    <nav class="py-2 bg-light border-bottom">
    <div class="container d-flex flex-wrap">
    <ul class="nav me-auto">
        <li class="nav-item"><a href="{% url 'algor:choose' %}" class="nav-link link-dark px-2 active" aria-current="page">Strona główna</a></li>
      </ul>
    </div>
    <div class="container d-flex flex-wrap justify-content-center">
      <a href="/" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">Algorytmy Sortowania</span>
      </a>
    </div>
</header>
<br>
<div class="container">
      {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                {% endfor %}
      {% endif %}
      {% block content %}
      {% endblock %}
  </div>


<footer>
    <div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="text-muted">Algorytmy i struktury danych 2022</span>
    </div>

  </footer>
</div>
</footer>
<!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
{% block additional_script %}
{% endblock %}
</body>
</html>